# MariaDB connection
jdbc.driverClass=org.mariadb.jdbc.Driver
jdbc.connectionURL=jdbc:mariadb://albeesoft.cafe24.com:3306/albeepoint
jdbc.userId=root
jdbc.password=dba3048!01

# Base packages for generated code
base.java.package=com.albee.albeepoint.mapper.base
base.xml.path=com/albee/albeepoint/mapper/base

# Target directories
# Java, Mapper interface, and Mapper XML are all generated under:
# src/main/java/com/albee/albeepoint/mapper/base/{table}
java.targetProject=src/main/java
resources.targetProject=src/main/java
